WITH CSUTOMER_LV AS (
    SELECT DISTINCT CUST_CODE
          ,DATE_TRUNC(PARSE_DATE('%Y%m%d', CAST(SHOP_DATE AS STRING)), MONTH) AS SHOP_MTH
    FROM `my-project-1541827391977.BADS7105.supermarket` 
    WHERE CUST_CODE IS NOT NULL ) 
SELECT RPT_MTH
      ,COUNT(DISTINCT CUST_CODE) AS CNT_CUST
      ,COUNt(DISTINCT CASE WHEN CUST_STATUS = 'New' THEN CUST_CODE ELSE "" END) AS CNT_NEW
      ,COUNt(DISTINCT CASE WHEN CUST_STATUS = 'Repeat' THEN CUST_CODE ELSE "" END) AS CNT_REPEAT
      ,COUNt(DISTINCT CASE WHEN CUST_STATUS = 'Reactive' THEN CUST_CODE ELSE "" END) AS CNT_REACTIVE
      ,COUNt(DISTINCT CASE WHEN CUST_STATUS = 'Churn' THEN CUST_CODE ELSE "" END) AS CNT_CHURN
FROM ((SELECT CUST_CODE
            ,SHOP_MTH AS RPT_MTH
            , PREV_MTH
            ,(CASE WHEN DATE_DIFF(SHOP_MTH, PREV_MTH, MONTH) IS NULL THEN 'New'
                   WHEN DATE_DIFF(SHOP_MTH, PREV_MTH, MONTH) = 1     THEN 'Repeat'
                   WHEN DATE_DIFF(SHOP_MTH, PREV_MTH, MONTH) > 1     THEN 'Reactive'
                   ELSE NULL END) AS CUST_STATUS
      FROM (SELECT CUST_CODE
                  ,SHOP_MTH
                  ,(LAG(SHOP_MTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MTH)) AS PREV_MTH
            FROM CSUTOMER_LV))
    UNION ALL
    (SELECT CUST_CODE
           ,DATE_ADD(SHOP_MTH, INTERVAL 1 MONTH) AS RPT_MTH
           ,SHOP_MTH as PREV_MTH
           ,'Churn' AS CUST_STATUS
     FROM (SELECT CUST_CODE
                 ,SHOP_MTH
                 ,DATE_DIFF(LEAD(SHOP_MTH, 1) OVER (PARTITION BY CUST_CODE ORDER BY SHOP_MTH), SHOP_MTH, MONTH) AS NEXT_MTH
           FROM CSUTOMER_LV) 
     WHERE (NEXT_MTH > 1 or NEXT_MTH is null) AND SHOP_MTH < (SELECT MAX(SHOP_MTH) FROM CSUTOMER_LV)))
GROUP BY RPT_MTH
;

